#!/bin/bash
# workspace-reset file hierarchy

WORKSPACE=/home/codio/workspace/
arg=$1
COUNT=10

function init_workspace {
  mkdir ${WORKSPACE}sqlexamples
  echo -e "-- Comments in SQL are written this way" > ${WORKSPACE}sql-examples/sql-example.sql
  echo -e "-- This is how SQL comments are written (just two dashes)\n\nUSE people;\n\nSELECT surname FROM names\nORDER BY surname DESC\nLIMIT 5;" > ${WORKSPACE}source-file.sql
  while (( COUNT > 0 ))
  do
    > ${WORKSPACE}/sql-1-$COUNT/sql-1-$COUNT.sql
    (( COUNT -- ))
  done
	echo "Project files have been reseted"
	sleep 2
	clear
}

function reset_workspace {
	echo -e "-- Comments in SQL are written this way" > ${WORKSPACE}people.sql
  echo -e "-- Comments in SQL are written this way" > ${WORKSPACE}birthdays.sql
  echo -e "-- Comments in SQL are written this way" > ${WORKSPACE}birthday-ids.sql
  rm -r ${WORKSPACE}sqlexamples
  echo ' ' > ~/.mysql_history
	echo "Reseting project files and directories"
	sleep 2
	init_workspace
}

case $arg in
	workspace ) reset_workspace
		;;
	* ) echo "'$arg' doesn't match any available arguments" 
		;;
esac